### ISSUE TITLE
Problems with ruby 1.9.2-preview3

### ISSUE THREAD

**Issue by bterkuile** [krobertson/dm-paperclip#10]
Creating a tempfile fails, the following patch solves it:
http://github.com/dwalters/paperclip/commit/2a85add5f102db8773518f8ac30f7e2337bf7d13

**Comment by ku1ik** [comment]
I can confirm that, it's an issue under 1.9.2preview3. I've monkey patched it that way: http://gist.github.com/445682 . I've left %d but did n.to_i instead.

**Comment by krobertson** [comment]
This issue was fixed in some recent changes.
