### ISSUE TITLE
Validations don't seem to work.

### ISSUE THREAD

**Issue by mindless** [krobertson/dm-paperclip#12]
Using this on Sinatra/Monk application. 

Uploading works beautifully but validations throw an undefined method error even if i've included DataMapper::Validate and Paperclip::Resource in my class and dm-validations is required before dm-paperclip in my init.rb.

Any suggestions?

**Comment by jamiltao** [comment]
You need to include the following lines in your paperclip.rb

config.use_dm_validations = true
