### ISSUE TITLE
Rails 3.0.3 issue with to_tempfile

### ISSUE THREAD

**Issue by dxg** [krobertson/dm-paperclip#14]
When uploading a file, you get:
NoMethodError (undefined method `to_tempfile' for #<ActionDispatch::Http::UploadedFile:...

Thoughtbot commit to resolve this is here:
https://github.com/thoughtbot/paperclip/commit/ef7233d25700a7e69cebd2334b656fa9ca0ae927

**Comment by krobertson** [comment]
Resolved in some recent updates.
