### ISSUE TITLE
#url appends datetimes to attachment url

### ISSUE THREAD

**Issue by Voker57** [krobertson/dm-paperclip#4]
I f i call mymodel.url, i get something like images/1/thumb/wtf.jpg?45346262346&346346346

I'd like to make this configurable, because i like clean URIs and it does not make any sense as i can see anyway, except for broken browsers.

**Comment by Voker57** [comment]
i see that already is fixed in git

**Comment by krobertson** [comment]
Have been out of the loop for a while.  Merging in changes, fixing tests, and will be posting a new version soon.
