### ISSUE TITLE
Dependecy on extlib kills routing in rails3

### ISSUE THREAD

**Issue by bterkuile** [krobertson/dm-paperclip#9]
Still busy testing, not even done an upload yet, but adding this to a rails3 setup kills the routing. For example for an url: pages/2 rails expects a controller named PagesesController. Commenting out require 'extlib' in paperclib solves this, but might give some other trouble :)

**Comment by gucki** [comment]
Just hit the same error: https://rails.lighthouseapp.com/projects/8994-ruby-on-rails/tickets/4857

**Comment by ku1ik** [comment]
Same here, looks like double pluralization happens.

**Comment by mbj** [comment]
I think you should not have to require 'extlib' it'll be required by dm-core if appropriate (when you are not in an active_support context). Extlib inferences badly with active_support.

I forked the repo and eliminated require 'extlib' in lib/dm-paperclip.rb no specs broken and rails3-beta4 is happy again.

until the autor fixes this issue you can use my repo http://github.com/mbj/dm-paperclip

**Comment by mbj** [comment]
hehe, my assumptions about specs are incorrect. the test helper does require 'extlib' for his self. So nothing is fixed in my repo :(

**Comment by mbj** [comment]
Now the specs/tests are not broken anymore. (except storage_test, dont got the library for aws/s3).

**Comment by quinn** [comment]
the new datamapper prefers activesupport over extlib: http://github.com/datamapper/dm-core/blob/master/lib/dm-core.rb#L10-52 shouldn't dm-paperclip do the same?

**Comment by ku1ik** [comment]
@quinn, probably, If dm-paperclip is plugin for DM and DM >=1.0 uses AS then new dm-paperclip release compatible with DM >=1.0 should use AS in my opinion.

**Comment by dkubb** [comment]
FYI, DM 1.1.0 removes the dependency on ActiveSupport _and_ Extlib. You can use whichever one is more appropriate to your environment, or neither if you like.
